name: Build pdf

on:
  push:
    paths:
      - '**.tex'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Build latex project
      uses: xu-cheng/latex-action@v3
      with:
        root_file: report.tex
        latexmk_use_lualatex: true
        working_directory: predstavlenie/
        extra_fonts: |
          ../fonts/*

    - name: Commit and Push Changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "chore(ci): build pdf" || echo "No changes to commit"
        git push

    - name: Upload pdf artifact
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: predstavlenie/*.pdf
      if: always()
